<?php


$partners = [
    ['name' => 'Armand Femme',      'picture' => 'armandf.png',            'categories' => ['vetements-femme'],                        'description' => 'Magasin de prêt à porter pour homme, Armand Thiery vous propose de renouveler votre garde robe avec le meilleur de la mode homme.' ],
    ['name' => 'Armand Homme',      'picture' => 'armandh.png',            'categories' => ['vetements-homme'] ,                       'description' => 'Magasin de prêt à porter pour femme, Armand Thiery vous propose de renouveler votre garde robe avec le meilleur de la mode femme.' ],
    ['name' => 'Au Pain Gourmand',  'picture' => 'aupaingourmand.png',     'categories' => ['alimentaire'],                            'description' => 'Boulangerie artisanale où tout est fabriqué sur place pains,viennoiseries, pâtisseries.' ],
    ['name' => 'Bershka',           'picture' => 'bershka.jpg',            'categories' => ['vetements-femme'],                        'description' => 'Renouvelez vos looks avec la mode pour femme de la Nouvelle Collection de Bershka. Les dernières tendances en matière de Robes. T-shirts, chaussures.' ],
    ['name' => 'Bio-coop',          'picture' => 'bio-coop.png',           'categories' => ['alimentaire'],                            'description' => 'Biocoop, premier réseau de magasins bio en France à proposer des produits bio, locaux et de saison, issus du commerce équitable.' ],
    ['name' => 'Carrefour City',    'picture' => 'carrefour-city.png',     'categories' => ['alimentaire'],                            'description' => 'Carrefour City est une enseigne de proximité pour des courses efficaces au cœur de la ville. Dans un cadre convivial et moderne, pour des achats du quotidien.' ],
    ['name' => 'Celio',             'picture' => 'celio.jpg',              'categories' => ['vetements-homme'],                        'description' => 'Profitez de la tendance masculine avec des vêtements de la marque Celio' ],
    ['name' => 'Cop-Copine',        'picture' => 'cop-copine.png',         'categories' => ['vetements-femme'],                        'description' => 'Vêtements pour femme, retrouvez des robes de la collection été a petit prix.' ],
    ['name' => 'Courir',            'picture' => 'courir.jpg',             'categories' => ['vetements-homme', 'vetements-femme'],     'description' => 'Les plus grandes marques de sneakers et baskets sont disponibles chez Courir. Nike, Adidas, Vans, Puma, Converse ... pour homme, femme et enfant.' ],
    ['name' => 'Guess',             'picture' => 'guess.jpg',              'categories' => ['vetements-homme', 'vetements-femme'],     'description' => 'Créez votre look avec les incontournables de cette saison. Découvrez les vêtements de la collection GUESS printemps-été: Vêtements, Jeans, Sacs.' ],
    ['name' => 'Julie-Laurent',     'picture' => 'julie-laurent.jpg',      'categories' => ['vetements-femme'],                        'description' => 'Julie Laurent conçoit et fabrique des vêtements féminins de qualité en éditions limitées à partir de tissus de haute couture' ],
    ['name' => 'Kaporal',           'picture' => 'kaporal.png',            'categories' => ['vetements-homme', 'vetements-femme'],     'description' => 'Composez des looks tendances, vintage, rétro, sport ou bien casual avec les vêtements pour homme des collections Kaporal.' ],
    ['name' => 'Lidl',              'picture' => 'lidl.png',               'categories' => ['alimentaire'],                            'description' => 'Faire ses courses rapidement chaque jour en profitant du meilleur rapport qualité/prix !' ],
    ['name' => 'M&O',               'picture' => 'm&o.png',                'categories' => ['alimentaire'],                            'description' => 'La Meute M&O, se sont des croquettes, friandise pour votre chien, chat ' ],
    ['name' => 'Mango',             'picture' => 'mango.png',              'categories' => ['vetements-homme', 'vetements-femme'],     'description' => 'Tendances de mode, de chaussures et accessoires de Mango ! Achetez les meilleurs looks pour cette saison' ],
    ['name' => 'Naf-naf',           'picture' => 'naf-naf.jpg',            'categories' => ['vetements-femme'],                        'description' => 'Vêtements pour femme, Profiter de la nouvelle collection Printemps-Été' ],
    ['name' => 'Olly-Gan',          'picture' => 'olly-gan.jpg',           'categories' => ['vetements-homme'],                        'description' => 'La marque de mode pour Hommes OLLYGAN. Chaussure, vêtement et accesoire de qualité.' ],
    ['name' => 'Pharmacie',         'picture' => 'pharmacie.jpg',          'categories' => ['autres'],                                 'description' => 'Votre parapharmacie et vos médicaments' ],
    ['name' => 'Pimkie',            'picture' => 'pimkie.jpg',             'categories' => ['vetements-femme'],                        'description' => ' Retrouve toute la collection de vêtements femme et accessoires tendance' ],
    ['name' => 'Quater-Back',       'picture' => 'quater-back.jpg',        'categories' => ['vetements-homme'],                        'description' => 'Quater Back, le propulseur de tendances' ],
    ['name' => 'Récré',             'picture' => 'recre',                  'categories' => ['autres'],                                 'description' => 'La Grande Récré tous les jouets pour filles et garçons.' ],
    ['name' => 'Spar',              'picture' => 'spar.jpg',               'categories' => ['alimentaire'],                            'description' => 'Spar est un enseigne de grande distribution à prédomminance alimentaire.' ],
    ['name' => 'SpringField',       'picture' => 'springfield.jpg',        'categories' => ['vetements-homme', 'vetements-femme'],     'description' => 'Springfield : Chemises, polos, robes, pantalons, jeans, jupes, vestes, manteaux, chaussures et accessoires.' ],
    ['name' => 'StreetShop',        'picture' => 'streetshop-cbd.jpg',     'categories' => ['autres'],                                 'description' => 'Fleurs CBD, graines de collection, HeadShop, VapoShop, Chicha, grinders et bien plus' ],
    ['name' => 'Undiz',             'picture' => 'undiz.png',              'categories' => ['vetements-homme', 'vetements-femme'],     'description' => 'Vente en ligne de lingerie femme et homme, maillot de bain, pyjama et loungewear / homewear.' ],
    ['name' => 'Valège',            'picture' => 'valege.jpg',             'categories' => ['vetements-femme'],                        'description' => 'La lingerie fine et sexy : soutien-gorge, shorty, string, maillot de bain' ],

];